// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using pi_projetolivros_banco;

#nullable disable

namespace pi_projetolivros.Migrations
{
    [DbContext(typeof(Banco))]
    [Migration("20260522025001_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("pi_projetolivros.DTO.Usuario.Seguidor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataSeguimento")
                        .HasColumnType("datetime2");

                    b.Property<int>("SeguidoId")
                        .HasColumnType("int");

                    b.Property<int>("SeguidorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SeguidoId");

                    b.HasIndex("SeguidorId");

                    b.ToTable("Seguidores");
                });

            modelBuilder.Entity("pi_projetolivros.Models.Banco.Avaliaco", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DataAvaliacao")
                        .HasColumnType("datetime")
                        .HasColumnName("data_avaliacao");

                    b.Property<int?>("LivroId")
                        .HasColumnType("int")
                        .HasColumnName("livro_id");

                    b.Property<int?>("Nota")
                        .HasColumnType("int")
                        .HasColumnName("nota");

                    b.Property<string>("Resenha")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("resenha");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("int")
                        .HasColumnName("usuario_id");

                    b.Property<int>("livro_id")
                        .HasColumnType("int");

                    b.Property<int>("usuario_id")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK_avaliacoes");

                    b.HasIndex("LivroId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("avaliacoes", null, t =>
                        {
                            t.Property("livro_id")
                                .HasColumnName("livro_id1");

                            t.Property("usuario_id")
                                .HasColumnName("usuario_id1");
                        });
                });

            modelBuilder.Entity("pi_projetolivros.Models.Banco.Favorito", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DataFavoritado")
                        .HasColumnType("datetime")
                        .HasColumnName("data_favoritado");

                    b.Property<int>("LivroId")
                        .HasColumnType("int")
                        .HasColumnName("livro_id");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id")
                        .HasName("PK_favoritos");

                    b.HasIndex("LivroId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("favoritos", (string)null);
                });

            modelBuilder.Entity("pi_projetolivros.Models.Banco.Grupo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataCriacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Descricao")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("FotoCapa")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("LiderId")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.HasIndex("LiderId");

                    b.ToTable("Grupos", (string)null);
                });

            modelBuilder.Entity("pi_projetolivros.Models.Banco.Livro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Autor")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("autor");

                    b.Property<string>("Isbn")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("isbn");

                    b.Property<string>("Temas")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("temas");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("titulo");

                    b.HasKey("Id")
                        .HasName("livros_pkey");

                    b.HasIndex(new[] { "Isbn" }, "livros_isbn_key")
                        .IsUnique()
                        .HasFilter("[isbn] IS NOT NULL");

                    b.ToTable("livros", (string)null);
                });

            modelBuilder.Entity("pi_projetolivros.Models.Banco.MensagemGrupo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Conteudo")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime>("DataPostagem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("GrupoId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GrupoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("MensagemGrupo", (string)null);
                });

            modelBuilder.Entity("pi_projetolivros.Models.Banco.Notificacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Conteudo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("DataCriacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<bool>("Lida")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Notificacoes", (string)null);
                });

            modelBuilder.Entity("pi_projetolivros.Models.Banco.PostGrupo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Conteudo")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("DataPostagem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("GrupoId")
                        .HasColumnType("int");

                    b.Property<int?>("PostPaiId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GrupoId");

                    b.HasIndex("PostPaiId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("PostGrupo", (string)null);
                });

            modelBuilder.Entity("pi_projetolivros.Models.Banco.SolicitacaoGrupo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataSolicitacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("GrupoId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GrupoId");

                    b.HasIndex("UsuarioId", "GrupoId")
                        .IsUnique();

                    b.ToTable("SolicitacaoGrupo", (string)null);
                });

            modelBuilder.Entity("pi_projetolivros.Models.Banco.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cidade")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("cidade");

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("descricao");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("email");

                    b.Property<string>("FotoPerfil")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("foto_perfil");

                    b.Property<int?>("Idade")
                        .HasColumnType("int")
                        .HasColumnName("idade");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nome");

                    b.Property<bool>("Premium")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("premium");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("senha");

                    b.HasKey("Id")
                        .HasName("usuarios_pkey");

                    b.HasIndex(new[] { "Email" }, "usuarios_email_key")
                        .IsUnique();

                    b.ToTable("usuarios", (string)null);
                });

            modelBuilder.Entity("pi_projetolivros.Models.Banco.UsuarioGrupo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataEntrada")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("GrupoId")
                        .HasColumnType("int");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GrupoId");

                    b.HasIndex("UsuarioId", "GrupoId")
                        .IsUnique();

                    b.ToTable("UsuarioGrupo", (string)null);
                });

            modelBuilder.Entity("pi_projetolivros.Models.Chat.CurtidaChat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataCurtida")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("MensagemId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MensagemId");

                    b.HasIndex("UsuarioId", "MensagemId")
                        .IsUnique();

                    b.ToTable("CurtidaChat", (string)null);
                });

            modelBuilder.Entity("pi_projetolivros.Models.Chat.MensagemChat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Conteudo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime>("DataPostagem")
                        .HasColumnType("datetime2");

                    b.Property<int?>("GrupoId")
                        .HasColumnType("int");

                    b.Property<int?>("MensagemPaiId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GrupoId");

                    b.HasIndex("MensagemPaiId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("MensagensChat");
                });

            modelBuilder.Entity("pi_projetolivros.Models.SituacaoLivro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DataAtualizacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("data_atualizacao")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int?>("LivroId")
                        .HasColumnType("int")
                        .HasColumnName("livro_id");

                    b.Property<string>("Status")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("status");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("int")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id")
                        .HasName("situacao_livros_pkey");

                    b.HasIndex("LivroId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("situacao_livros", (string)null);
                });

            modelBuilder.Entity("pi_projetolivros.DTO.Usuario.Seguidor", b =>
                {
                    b.HasOne("pi_projetolivros.Models.Banco.Usuario", "SeguidoUsuario")
                        .WithMany()
                        .HasForeignKey("SeguidoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("pi_projetolivros.Models.Banco.Usuario", "SeguidorUsuario")
                        .WithMany()
                        .HasForeignKey("SeguidorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SeguidoUsuario");

                    b.Navigation("SeguidorUsuario");
                });

            modelBuilder.Entity("pi_projetolivros.Models.Banco.Avaliaco", b =>
                {
                    b.HasOne("pi_projetolivros.Models.Banco.Livro", "Livro")
                        .WithMany()
                        .HasForeignKey("LivroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK_Livro_Avaliacao");

                    b.HasOne("pi_projetolivros.Models.Banco.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK_Usuario_Avaliacao");

                    b.Navigation("Livro");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("pi_projetolivros.Models.Banco.Favorito", b =>
                {
                    b.HasOne("pi_projetolivros.Models.Banco.Livro", "Livro")
                        .WithMany()
                        .HasForeignKey("LivroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Fav_Livro");

                    b.HasOne("pi_projetolivros.Models.Banco.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Fav_Usuario");

                    b.Navigation("Livro");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("pi_projetolivros.Models.Banco.Grupo", b =>
                {
                    b.HasOne("pi_projetolivros.Models.Banco.Usuario", "Lider")
                        .WithMany()
                        .HasForeignKey("LiderId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_Grupos_Lider");

                    b.Navigation("Lider");
                });

            modelBuilder.Entity("pi_projetolivros.Models.Banco.MensagemGrupo", b =>
                {
                    b.HasOne("pi_projetolivros.Models.Banco.Grupo", "Grupo")
                        .WithMany()
                        .HasForeignKey("GrupoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("pi_projetolivros.Models.Banco.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Grupo");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("pi_projetolivros.Models.Banco.Notificacao", b =>
                {
                    b.HasOne("pi_projetolivros.Models.Banco.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Notificacoes_Usuarios");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("pi_projetolivros.Models.Banco.PostGrupo", b =>
                {
                    b.HasOne("pi_projetolivros.Models.Banco.Grupo", "Grupo")
                        .WithMany()
                        .HasForeignKey("GrupoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("pi_projetolivros.Models.Banco.PostGrupo", "PostPai")
                        .WithMany("Respostas")
                        .HasForeignKey("PostPaiId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("pi_projetolivros.Models.Banco.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Grupo");

                    b.Navigation("PostPai");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("pi_projetolivros.Models.Banco.SolicitacaoGrupo", b =>
                {
                    b.HasOne("pi_projetolivros.Models.Banco.Grupo", "Grupo")
                        .WithMany()
                        .HasForeignKey("GrupoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("pi_projetolivros.Models.Banco.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Grupo");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("pi_projetolivros.Models.Banco.UsuarioGrupo", b =>
                {
                    b.HasOne("pi_projetolivros.Models.Banco.Grupo", "Grupo")
                        .WithMany("Membros")
                        .HasForeignKey("GrupoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("pi_projetolivros.Models.Banco.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Grupo");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("pi_projetolivros.Models.Chat.CurtidaChat", b =>
                {
                    b.HasOne("pi_projetolivros.Models.Chat.MensagemChat", "Mensagem")
                        .WithMany("Curtidas")
                        .HasForeignKey("MensagemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("pi_projetolivros.Models.Banco.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Mensagem");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("pi_projetolivros.Models.Chat.MensagemChat", b =>
                {
                    b.HasOne("pi_projetolivros.Models.Banco.Grupo", "Grupo")
                        .WithMany()
                        .HasForeignKey("GrupoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("pi_projetolivros.Models.Chat.MensagemChat", "MensagemPai")
                        .WithMany("Respostas")
                        .HasForeignKey("MensagemPaiId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("pi_projetolivros.Models.Banco.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Grupo");

                    b.Navigation("MensagemPai");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("pi_projetolivros.Models.SituacaoLivro", b =>
                {
                    b.HasOne("pi_projetolivros.Models.Banco.Livro", "Livro")
                        .WithMany("SituacaoLivros")
                        .HasForeignKey("LivroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("situacao_livros_livro_id_fkey");

                    b.HasOne("pi_projetolivros.Models.Banco.Usuario", "Usuario")
                        .WithMany("SituacaoLivros")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("situacao_livros_usuario_id_fkey");

                    b.Navigation("Livro");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("pi_projetolivros.Models.Banco.Grupo", b =>
                {
                    b.Navigation("Membros");
                });

            modelBuilder.Entity("pi_projetolivros.Models.Banco.Livro", b =>
                {
                    b.Navigation("SituacaoLivros");
                });

            modelBuilder.Entity("pi_projetolivros.Models.Banco.PostGrupo", b =>
                {
                    b.Navigation("Respostas");
                });

            modelBuilder.Entity("pi_projetolivros.Models.Banco.Usuario", b =>
                {
                    b.Navigation("SituacaoLivros");
                });

            modelBuilder.Entity("pi_projetolivros.Models.Chat.MensagemChat", b =>
                {
                    b.Navigation("Curtidas");

                    b.Navigation("Respostas");
                });
#pragma warning restore 612, 618
        }
    }
}
